---
- hosts: local
  tasks:
#    - name: Runtime include
#      include_tasks: common_tasks2.yml
#      tags: foo1

    - name: Import (pre-processed at playbook parsing)
      import_tasks: common_tasks2.yml
      tags: foo1
