---
- hosts: local
  tasks:
#    - name: Runtime with loop
#      include_tasks: common_tasks.yml
#      loop:
#        - 10.1.1.1
#        - 10.1.1.2
#        - 10.1.1.3
#        - 10.1.1.4

    - name: Import (pre-processed at playbook parsing) - will fail
      import_tasks: common_tasks_w_loop.yml
      #import_tasks: common_tasks.yml
      #loop:
      #  - 10.1.1.1
      #  - 10.1.1.2
      #  - 10.1.1.3
      #  - 10.1.1.4
