---
- name: Global configuration
  hosts: cisco:arista:nxos
  gather_facts: True
  tasks:
    - name: IOS global config
      cisco.ios.ios_config:
        lines:
          - "ip name-server {{ dns_server1 }}"
          - "ip name-server {{ dns_server2 }}"
          - "ip domain name {{ domain_name }}"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
        save_when: changed
      when: ansible_facts.net_iostype is defined and 
            ansible_facts.net_iostype == "IOS"

    - name: IOS-XE global config
      cisco.ios.ios_config:
        lines:
          - "ip name-server {{ dns_server1 }} {{ dns_server2 }}"
          - "ip domain name {{ domain_name }}"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
        save_when: changed
      when: ansible_facts.net_iostype is defined and
            ansible_facts.net_iostype == "IOS-XE"

    - name: EOS global config
      arista.eos.eos_config:
        lines:
          - "ip name-server {{ dns_server1 }}"
          - "ip name-server {{ dns_server2 }}"
          - "ip domain-name {{ domain_name }}"
          - "ntp server {{ ntp_server1 }}"
          - "ntp server {{ ntp_server2 }}"
        save_when: changed
      when: 'ansible_network_os == "eos"'

    - name: NX-OS global config
      cisco.nxos.nxos_config:
        lines:
          - "ip domain-name {{ domain_name }}"
          - "ip name-server {{ dns_server1 }} {{ dns_server2 }}"
          - "ntp server {{ ntp_server1 }} use-vrf management"
          - "ntp server {{ ntp_server2 }} use-vrf default"
        save_when: changed
      when: 'ansible_network_os == "nxos"'
      tags: nxos

- name: Global configuration
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Juniper global config
      junipernetworks.junos.junos_config:
        lines:
          - "set system name-server {{ dns_server1 }}"
          - "set system name-server {{ dns_server2 }}"
          - "set system domain-name {{ domain_name }}"
          - "set system ntp server {{ ntp_server1 }}"
          - "set system ntp server {{ ntp_server2 }}"
      tags: junos
