---
- name: Hello we're going print this to the screen
  hosts: arista:cisco:nxos1
  gather_facts: False
  tasks:
    - ansible.builtin.ping:

    - ansible.builtin.ping:

    - ansible.builtin.ping:
